// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ise_car_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IseCarApiServiceClient is the client API for IseCarApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IseCarApiServiceClient interface {
	// DescribeCarV1 - Describe a car
	DescribeCarV1(ctx context.Context, in *DescribeCarV1Request, opts ...grpc.CallOption) (*DescribeCarV1Response, error)
	// ListCarsV1 - List existing cars
	ListCarsV1(ctx context.Context, in *ListCarsV1Request, opts ...grpc.CallOption) (*ListCarsV1Response, error)
	// CreateCarV1 - create new car
	CreateCarV1(ctx context.Context, in *CreateCarV1Request, opts ...grpc.CallOption) (*CreateCarV1Response, error)
	// RemoveCarV1 - remove car by id
	RemoveCarV1(ctx context.Context, in *RemoveCarV1Request, opts ...grpc.CallOption) (*RemoveCarV1Response, error)
}

type iseCarApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIseCarApiServiceClient(cc grpc.ClientConnInterface) IseCarApiServiceClient {
	return &iseCarApiServiceClient{cc}
}

func (c *iseCarApiServiceClient) DescribeCarV1(ctx context.Context, in *DescribeCarV1Request, opts ...grpc.CallOption) (*DescribeCarV1Response, error) {
	out := new(DescribeCarV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.ise_car_api.v1.IseCarApiService/DescribeCarV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iseCarApiServiceClient) ListCarsV1(ctx context.Context, in *ListCarsV1Request, opts ...grpc.CallOption) (*ListCarsV1Response, error) {
	out := new(ListCarsV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.ise_car_api.v1.IseCarApiService/ListCarsV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iseCarApiServiceClient) CreateCarV1(ctx context.Context, in *CreateCarV1Request, opts ...grpc.CallOption) (*CreateCarV1Response, error) {
	out := new(CreateCarV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.ise_car_api.v1.IseCarApiService/CreateCarV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iseCarApiServiceClient) RemoveCarV1(ctx context.Context, in *RemoveCarV1Request, opts ...grpc.CallOption) (*RemoveCarV1Response, error) {
	out := new(RemoveCarV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.ise_car_api.v1.IseCarApiService/RemoveCarV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IseCarApiServiceServer is the server API for IseCarApiService service.
// All implementations must embed UnimplementedIseCarApiServiceServer
// for forward compatibility
type IseCarApiServiceServer interface {
	// DescribeCarV1 - Describe a car
	DescribeCarV1(context.Context, *DescribeCarV1Request) (*DescribeCarV1Response, error)
	// ListCarsV1 - List existing cars
	ListCarsV1(context.Context, *ListCarsV1Request) (*ListCarsV1Response, error)
	// CreateCarV1 - create new car
	CreateCarV1(context.Context, *CreateCarV1Request) (*CreateCarV1Response, error)
	// RemoveCarV1 - remove car by id
	RemoveCarV1(context.Context, *RemoveCarV1Request) (*RemoveCarV1Response, error)
	mustEmbedUnimplementedIseCarApiServiceServer()
}

// UnimplementedIseCarApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIseCarApiServiceServer struct {
}

func (UnimplementedIseCarApiServiceServer) DescribeCarV1(context.Context, *DescribeCarV1Request) (*DescribeCarV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeCarV1 not implemented")
}
func (UnimplementedIseCarApiServiceServer) ListCarsV1(context.Context, *ListCarsV1Request) (*ListCarsV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCarsV1 not implemented")
}
func (UnimplementedIseCarApiServiceServer) CreateCarV1(context.Context, *CreateCarV1Request) (*CreateCarV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCarV1 not implemented")
}
func (UnimplementedIseCarApiServiceServer) RemoveCarV1(context.Context, *RemoveCarV1Request) (*RemoveCarV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCarV1 not implemented")
}
func (UnimplementedIseCarApiServiceServer) mustEmbedUnimplementedIseCarApiServiceServer() {}

// UnsafeIseCarApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IseCarApiServiceServer will
// result in compilation errors.
type UnsafeIseCarApiServiceServer interface {
	mustEmbedUnimplementedIseCarApiServiceServer()
}

func RegisterIseCarApiServiceServer(s grpc.ServiceRegistrar, srv IseCarApiServiceServer) {
	s.RegisterService(&IseCarApiService_ServiceDesc, srv)
}

func _IseCarApiService_DescribeCarV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeCarV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IseCarApiServiceServer).DescribeCarV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.ise_car_api.v1.IseCarApiService/DescribeCarV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IseCarApiServiceServer).DescribeCarV1(ctx, req.(*DescribeCarV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _IseCarApiService_ListCarsV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCarsV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IseCarApiServiceServer).ListCarsV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.ise_car_api.v1.IseCarApiService/ListCarsV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IseCarApiServiceServer).ListCarsV1(ctx, req.(*ListCarsV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _IseCarApiService_CreateCarV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCarV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IseCarApiServiceServer).CreateCarV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.ise_car_api.v1.IseCarApiService/CreateCarV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IseCarApiServiceServer).CreateCarV1(ctx, req.(*CreateCarV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _IseCarApiService_RemoveCarV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCarV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IseCarApiServiceServer).RemoveCarV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.ise_car_api.v1.IseCarApiService/RemoveCarV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IseCarApiServiceServer).RemoveCarV1(ctx, req.(*RemoveCarV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// IseCarApiService_ServiceDesc is the grpc.ServiceDesc for IseCarApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IseCarApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozonmp.ise_car_api.v1.IseCarApiService",
	HandlerType: (*IseCarApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeCarV1",
			Handler:    _IseCarApiService_DescribeCarV1_Handler,
		},
		{
			MethodName: "ListCarsV1",
			Handler:    _IseCarApiService_ListCarsV1_Handler,
		},
		{
			MethodName: "CreateCarV1",
			Handler:    _IseCarApiService_CreateCarV1_Handler,
		},
		{
			MethodName: "RemoveCarV1",
			Handler:    _IseCarApiService_RemoveCarV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ozonmp/ise_car_api/v1/ise_car_api.proto",
}
