// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ozonmp/ise_car_api/v1/ise_car_api.proto

package ise_car_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Car with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Car) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for CarInfo

	// no validation rules for UserId

	// no validation rules for TotalPrice

	// no validation rules for RiskRate

	// no validation rules for CircsLink

	return nil
}

// CarValidationError is the validation error returned by Car.Validate if the
// designated constraints aren't met.
type CarValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CarValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CarValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CarValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CarValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CarValidationError) ErrorName() string { return "CarValidationError" }

// Error satisfies the builtin error interface
func (e CarValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCar.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CarValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CarValidationError{}

// Validate checks the field values on GetCarV1Request with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetCarV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetCarId() <= 0 {
		return GetCarV1RequestValidationError{
			field:  "CarId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// GetCarV1RequestValidationError is the validation error returned by
// GetCarV1Request.Validate if the designated constraints aren't met.
type GetCarV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCarV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCarV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCarV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCarV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCarV1RequestValidationError) ErrorName() string { return "GetCarV1RequestValidationError" }

// Error satisfies the builtin error interface
func (e GetCarV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCarV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCarV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCarV1RequestValidationError{}

// Validate checks the field values on GetCarV1Response with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetCarV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetCarV1ResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// GetCarV1ResponseValidationError is the validation error returned by
// GetCarV1Response.Validate if the designated constraints aren't met.
type GetCarV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCarV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCarV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCarV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCarV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCarV1ResponseValidationError) ErrorName() string { return "GetCarV1ResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetCarV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCarV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCarV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCarV1ResponseValidationError{}

// Validate checks the field values on AddCarV1Request with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *AddCarV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetCarInfo()); l < 1 || l > 100 {
		return AddCarV1RequestValidationError{
			field:  "CarInfo",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
	}

	if m.GetUserId() <= 0 {
		return AddCarV1RequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
	}

	if m.GetTotalPrice() <= 0 {
		return AddCarV1RequestValidationError{
			field:  "TotalPrice",
			reason: "value must be greater than 0",
		}
	}

	if m.GetRiskRate() <= 0 {
		return AddCarV1RequestValidationError{
			field:  "RiskRate",
			reason: "value must be greater than 0",
		}
	}

	if l := utf8.RuneCountInString(m.GetCircsLink()); l < 1 || l > 100 {
		return AddCarV1RequestValidationError{
			field:  "CircsLink",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
	}

	return nil
}

// AddCarV1RequestValidationError is the validation error returned by
// AddCarV1Request.Validate if the designated constraints aren't met.
type AddCarV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddCarV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddCarV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddCarV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddCarV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddCarV1RequestValidationError) ErrorName() string { return "AddCarV1RequestValidationError" }

// Error satisfies the builtin error interface
func (e AddCarV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddCarV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddCarV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddCarV1RequestValidationError{}

// Validate checks the field values on AddCarV1Response with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *AddCarV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for CarId

	return nil
}

// AddCarV1ResponseValidationError is the validation error returned by
// AddCarV1Response.Validate if the designated constraints aren't met.
type AddCarV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddCarV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddCarV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddCarV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddCarV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddCarV1ResponseValidationError) ErrorName() string { return "AddCarV1ResponseValidationError" }

// Error satisfies the builtin error interface
func (e AddCarV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddCarV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddCarV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddCarV1ResponseValidationError{}

// Validate checks the field values on ListCarsV1Request with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *ListCarsV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetCursor() <= 0 {
		return ListCarsV1RequestValidationError{
			field:  "Cursor",
			reason: "value must be greater than 0",
		}
	}

	if m.GetLimit() <= 0 {
		return ListCarsV1RequestValidationError{
			field:  "Limit",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// ListCarsV1RequestValidationError is the validation error returned by
// ListCarsV1Request.Validate if the designated constraints aren't met.
type ListCarsV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCarsV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCarsV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCarsV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCarsV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCarsV1RequestValidationError) ErrorName() string {
	return "ListCarsV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListCarsV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCarsV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCarsV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCarsV1RequestValidationError{}

// Validate checks the field values on ListCarsV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListCarsV1Response) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetCars() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListCarsV1ResponseValidationError{
					field:  fmt.Sprintf("Cars[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListCarsV1ResponseValidationError is the validation error returned by
// ListCarsV1Response.Validate if the designated constraints aren't met.
type ListCarsV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCarsV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCarsV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCarsV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCarsV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCarsV1ResponseValidationError) ErrorName() string {
	return "ListCarsV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListCarsV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCarsV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCarsV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCarsV1ResponseValidationError{}

// Validate checks the field values on RemoveCarV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemoveCarV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetCarId() <= 0 {
		return RemoveCarV1RequestValidationError{
			field:  "CarId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// RemoveCarV1RequestValidationError is the validation error returned by
// RemoveCarV1Request.Validate if the designated constraints aren't met.
type RemoveCarV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveCarV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveCarV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveCarV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveCarV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveCarV1RequestValidationError) ErrorName() string {
	return "RemoveCarV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveCarV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveCarV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveCarV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveCarV1RequestValidationError{}

// Validate checks the field values on RemoveCarV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemoveCarV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Found

	return nil
}

// RemoveCarV1ResponseValidationError is the validation error returned by
// RemoveCarV1Response.Validate if the designated constraints aren't met.
type RemoveCarV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveCarV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveCarV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveCarV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveCarV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveCarV1ResponseValidationError) ErrorName() string {
	return "RemoveCarV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveCarV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveCarV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveCarV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveCarV1ResponseValidationError{}
