// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ise_car_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IseCarApiServiceClient is the client API for IseCarApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IseCarApiServiceClient interface {
	// GetCarV1 - Get a car by id
	GetCarV1(ctx context.Context, in *GetCarV1Request, opts ...grpc.CallOption) (*GetCarV1Response, error)
	// ListCarsV1 - List existing cars
	ListCarsV1(ctx context.Context, in *ListCarsV1Request, opts ...grpc.CallOption) (*ListCarsV1Response, error)
	// AddCarV1 - create new car
	AddCarV1(ctx context.Context, in *AddCarV1Request, opts ...grpc.CallOption) (*AddCarV1Response, error)
	// RemoveCarV1 - remove car by id
	RemoveCarV1(ctx context.Context, in *RemoveCarV1Request, opts ...grpc.CallOption) (*RemoveCarV1Response, error)
}

type iseCarApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIseCarApiServiceClient(cc grpc.ClientConnInterface) IseCarApiServiceClient {
	return &iseCarApiServiceClient{cc}
}

func (c *iseCarApiServiceClient) GetCarV1(ctx context.Context, in *GetCarV1Request, opts ...grpc.CallOption) (*GetCarV1Response, error) {
	out := new(GetCarV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.ise_car_api.v1.IseCarApiService/GetCarV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iseCarApiServiceClient) ListCarsV1(ctx context.Context, in *ListCarsV1Request, opts ...grpc.CallOption) (*ListCarsV1Response, error) {
	out := new(ListCarsV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.ise_car_api.v1.IseCarApiService/ListCarsV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iseCarApiServiceClient) AddCarV1(ctx context.Context, in *AddCarV1Request, opts ...grpc.CallOption) (*AddCarV1Response, error) {
	out := new(AddCarV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.ise_car_api.v1.IseCarApiService/AddCarV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iseCarApiServiceClient) RemoveCarV1(ctx context.Context, in *RemoveCarV1Request, opts ...grpc.CallOption) (*RemoveCarV1Response, error) {
	out := new(RemoveCarV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.ise_car_api.v1.IseCarApiService/RemoveCarV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IseCarApiServiceServer is the server API for IseCarApiService service.
// All implementations must embed UnimplementedIseCarApiServiceServer
// for forward compatibility
type IseCarApiServiceServer interface {
	// GetCarV1 - Get a car by id
	GetCarV1(context.Context, *GetCarV1Request) (*GetCarV1Response, error)
	// ListCarsV1 - List existing cars
	ListCarsV1(context.Context, *ListCarsV1Request) (*ListCarsV1Response, error)
	// AddCarV1 - create new car
	AddCarV1(context.Context, *AddCarV1Request) (*AddCarV1Response, error)
	// RemoveCarV1 - remove car by id
	RemoveCarV1(context.Context, *RemoveCarV1Request) (*RemoveCarV1Response, error)
	mustEmbedUnimplementedIseCarApiServiceServer()
}

// UnimplementedIseCarApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIseCarApiServiceServer struct {
}

func (UnimplementedIseCarApiServiceServer) GetCarV1(context.Context, *GetCarV1Request) (*GetCarV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCarV1 not implemented")
}
func (UnimplementedIseCarApiServiceServer) ListCarsV1(context.Context, *ListCarsV1Request) (*ListCarsV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCarsV1 not implemented")
}
func (UnimplementedIseCarApiServiceServer) AddCarV1(context.Context, *AddCarV1Request) (*AddCarV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCarV1 not implemented")
}
func (UnimplementedIseCarApiServiceServer) RemoveCarV1(context.Context, *RemoveCarV1Request) (*RemoveCarV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCarV1 not implemented")
}
func (UnimplementedIseCarApiServiceServer) mustEmbedUnimplementedIseCarApiServiceServer() {}

// UnsafeIseCarApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IseCarApiServiceServer will
// result in compilation errors.
type UnsafeIseCarApiServiceServer interface {
	mustEmbedUnimplementedIseCarApiServiceServer()
}

func RegisterIseCarApiServiceServer(s grpc.ServiceRegistrar, srv IseCarApiServiceServer) {
	s.RegisterService(&IseCarApiService_ServiceDesc, srv)
}

func _IseCarApiService_GetCarV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCarV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IseCarApiServiceServer).GetCarV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.ise_car_api.v1.IseCarApiService/GetCarV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IseCarApiServiceServer).GetCarV1(ctx, req.(*GetCarV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _IseCarApiService_ListCarsV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCarsV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IseCarApiServiceServer).ListCarsV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.ise_car_api.v1.IseCarApiService/ListCarsV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IseCarApiServiceServer).ListCarsV1(ctx, req.(*ListCarsV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _IseCarApiService_AddCarV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCarV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IseCarApiServiceServer).AddCarV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.ise_car_api.v1.IseCarApiService/AddCarV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IseCarApiServiceServer).AddCarV1(ctx, req.(*AddCarV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _IseCarApiService_RemoveCarV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCarV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IseCarApiServiceServer).RemoveCarV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.ise_car_api.v1.IseCarApiService/RemoveCarV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IseCarApiServiceServer).RemoveCarV1(ctx, req.(*RemoveCarV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// IseCarApiService_ServiceDesc is the grpc.ServiceDesc for IseCarApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IseCarApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozonmp.ise_car_api.v1.IseCarApiService",
	HandlerType: (*IseCarApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCarV1",
			Handler:    _IseCarApiService_GetCarV1_Handler,
		},
		{
			MethodName: "ListCarsV1",
			Handler:    _IseCarApiService_ListCarsV1_Handler,
		},
		{
			MethodName: "AddCarV1",
			Handler:    _IseCarApiService_AddCarV1_Handler,
		},
		{
			MethodName: "RemoveCarV1",
			Handler:    _IseCarApiService_RemoveCarV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ozonmp/ise_car_api/v1/ise_car_api.proto",
}
