# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ozonmp/ise_car_api/v1/ise_car_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ozonmp/ise_car_api/v1/ise_car_api.proto',
  package='ozonmp.ise_car_api.v1',
  syntax='proto3',
  serialized_options=_b('Z9github.com/ozonmp/ise-car-api/pkg/ise-car-api;ise_car_api'),
  serialized_pb=_b('\n\'ozonmp/ise_car_api/v1/ise_car_api.proto\x12\x15ozonmp.ise_car_api.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n\x03\x43\x61r\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n\x03\x66oo\x18\x02 \x01(\x04R\x03\x66oo\x12\x34\n\x07\x63reated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x07\x63reated\"6\n\x14\x44\x65scribeCarV1Request\x12\x1e\n\x06\x63\x61r_id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00R\x05\x63\x61rId\"I\n\x15\x44\x65scribeCarV1Response\x12\x30\n\x05value\x18\x01 \x01(\x0b\x32\x1a.ozonmp.ise_car_api.v1.CarR\x05value2\x9a\x01\n\x10IseCarApiService\x12\x85\x01\n\rDescribeCarV1\x12+.ozonmp.ise_car_api.v1.DescribeCarV1Request\x1a,.ozonmp.ise_car_api.v1.DescribeCarV1Response\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/cars/{car_id}B;Z9github.com/ozonmp/ise-car-api/pkg/ise-car-api;ise_car_apib\x06proto3')
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_CAR = _descriptor.Descriptor(
  name='Car',
  full_name='ozonmp.ise_car_api.v1.Car',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ozonmp.ise_car_api.v1.Car.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='foo', full_name='ozonmp.ise_car_api.v1.Car.foo', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='foo', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='ozonmp.ise_car_api.v1.Car.created', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='created', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=247,
)


_DESCRIBECARV1REQUEST = _descriptor.Descriptor(
  name='DescribeCarV1Request',
  full_name='ozonmp.ise_car_api.v1.DescribeCarV1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='car_id', full_name='ozonmp.ise_car_api.v1.DescribeCarV1Request.car_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\372B\0042\002 \000'), json_name='carId', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=303,
)


_DESCRIBECARV1RESPONSE = _descriptor.Descriptor(
  name='DescribeCarV1Response',
  full_name='ozonmp.ise_car_api.v1.DescribeCarV1Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ozonmp.ise_car_api.v1.DescribeCarV1Response.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='value', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=378,
)

_CAR.fields_by_name['created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DESCRIBECARV1RESPONSE.fields_by_name['value'].message_type = _CAR
DESCRIPTOR.message_types_by_name['Car'] = _CAR
DESCRIPTOR.message_types_by_name['DescribeCarV1Request'] = _DESCRIBECARV1REQUEST
DESCRIPTOR.message_types_by_name['DescribeCarV1Response'] = _DESCRIBECARV1RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Car = _reflection.GeneratedProtocolMessageType('Car', (_message.Message,), dict(
  DESCRIPTOR = _CAR,
  __module__ = 'ozonmp.ise_car_api.v1.ise_car_api_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.ise_car_api.v1.Car)
  ))
_sym_db.RegisterMessage(Car)

DescribeCarV1Request = _reflection.GeneratedProtocolMessageType('DescribeCarV1Request', (_message.Message,), dict(
  DESCRIPTOR = _DESCRIBECARV1REQUEST,
  __module__ = 'ozonmp.ise_car_api.v1.ise_car_api_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.ise_car_api.v1.DescribeCarV1Request)
  ))
_sym_db.RegisterMessage(DescribeCarV1Request)

DescribeCarV1Response = _reflection.GeneratedProtocolMessageType('DescribeCarV1Response', (_message.Message,), dict(
  DESCRIPTOR = _DESCRIBECARV1RESPONSE,
  __module__ = 'ozonmp.ise_car_api.v1.ise_car_api_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.ise_car_api.v1.DescribeCarV1Response)
  ))
_sym_db.RegisterMessage(DescribeCarV1Response)


DESCRIPTOR._options = None
_DESCRIBECARV1REQUEST.fields_by_name['car_id']._options = None

_ISECARAPISERVICE = _descriptor.ServiceDescriptor(
  name='IseCarApiService',
  full_name='ozonmp.ise_car_api.v1.IseCarApiService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=381,
  serialized_end=535,
  methods=[
  _descriptor.MethodDescriptor(
    name='DescribeCarV1',
    full_name='ozonmp.ise_car_api.v1.IseCarApiService.DescribeCarV1',
    index=0,
    containing_service=None,
    input_type=_DESCRIBECARV1REQUEST,
    output_type=_DESCRIBECARV1RESPONSE,
    serialized_options=_b('\202\323\344\223\002\023\022\021/v1/cars/{car_id}'),
  ),
])
_sym_db.RegisterServiceDescriptor(_ISECARAPISERVICE)

DESCRIPTOR.services_by_name['IseCarApiService'] = _ISECARAPISERVICE

# @@protoc_insertion_point(module_scope)
