// Code generated by "stringer -linecomment -type=EventStatus"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Available-1]
	_ = x[InProcess-2]
}

const _EventStatus_name = "availablein_process"

var _EventStatus_index = [...]uint8{0, 9, 19}

func (i EventStatus) String() string {
	i -= 1
	if i >= EventStatus(len(_EventStatus_index)-1) {
		return "EventStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EventStatus_name[_EventStatus_index[i]:_EventStatus_index[i+1]]
}
